#
# Todo: this language specification doens't seem to work with
# multiple OSs. The install still proceeds ok for now.
#
language: cpp

os:
  - linux
  - osx

# 
# Prepare autotools and install dependencies before installation
#
before_install:
  # 
  # Use GNU autotools to generate ./configure automatically
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      mkdir m4 ;
      autoreconf -i ;
      autoconf ;
      automake -a --gnu ;
    fi
  # 
  # Install GSL and Boost
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get install libgsl0-dev ;
      sudo apt-get install libboost-all-dev ;
    fi
  # 
  # We cannot use the ubuntu HDF5 package because it sets the
  # compatibility version to the old format (I'm not sure why), so
  # install it from source. Newer versions of the Ubuntu HDF5
  # package do not have this problem, but Travis uses 12.04 LTS.
  # We download a new version and compile manually from source.
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.15-patch1.tar.gz ;
      tar -xzf hdf5-1.8.15-patch1.tar.gz ;
      cd hdf5-1.8.15-patch1 && ./configure --build=x86_64-unknown-linux-gnu --prefix=/usr && make > /dev/null 2> /dev/null && sudo make install && cd .. ;
    fi

#
# Installation script
#
install:
  # 
  # Perform the installation on linux. Since there is no documentation,
  # 'make blank-doc' is used to create dummy documentation so that
  # 'make install' does not fail. At the end, 'acol --version' is used
  # to double check that the install worked.
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      ./configure && make blank-doc && make && make install && make check && acol --version ;
    fi
  # 
  # Use homebrew to install the development version on OSX. At the end,
  # 'acol --version' is used to double check that the install worked.
  # 
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew install homebrew/science/hdf5 && brew tap awsteiner/science && brew install o2scl --with-check --devel && acol --version ;
    fi

notifications:
  email:
    on_success: never
    on_failure: never