language: cpp

os:
  - linux
  - osx

before_install:
  # 
  # Use GNU autotools to generate ./configure automatically
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      mkdir m4 ;
      autoreconf -i ;
      autoconf ;
      automake -a --gnu ;
    fi
  # 
  # Install GSL and Boost
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get install libgsl0-dev ;
      sudo apt-get install libboost-all-dev ;
    fi
  # 
  # We cannot use the ubuntu HDF5 package because it sets the
  # compatibility version to the old format (I'm not sure why), so
  # install it from source. Newer versions of the Ubuntu HDF5
  # package do not have this problem, but Travis uses 12.04 LTS.
  # We download a new version and compile manually from source.
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.15-patch1.tar.gz ;
      tar -xzf hdf5-1.8.15-patch1.tar.gz ;
      cd hdf5-1.8.15-patch1 && ./configure --build=x86_64-unknown-linux-gnu --prefix=/usr && make > /dev/null 2> /dev/null && sudo make install && cd .. ;
    fi

#
# Use script instead of install because it continues after errors
#
script:
  # 
  # Perform the installation on linux, and run acol --version to see if
  # it works
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      ./configure && make && make install && make check && acol --version;
    fi
  # 
  # Use homebrew to install the development version on OSX
  # 
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew install homebrew/science/hdf5 && brew tap awsteiner/science && brew install o2scl --with-check --devel && acol --version ;
    fi

notifications:
  email:
    on_success: never
    on_failure: never