#
# Todo: this language specification doens't seem to work with
# multiple OSs. The install still proceeds ok for now.
#
language: cpp

os:
  - linux
  - osx

#
# Todo: Fix OSX build
#
matrix:
  allow_failures:
    - os: osx
    
# 
# Prepare autotools and install dependencies before installation
#
before_install:
  # 
  # Use GNU autotools to generate ./configure automatically on linux
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      mkdir m4 ;
      autoreconf -i ;
    fi
  # 
  # Install GSL and Boost
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-get install libgsl0-dev && sudo apt-get install libboost-all-dev;
    fi
  # 
  # The ubuntu HDF5 package cannot be used because it is configured to
  # be compatibile only the with older API. Newer versions of the
  # Ubuntu HDF5 package do not have this problem, but Travis uses
  # 12.04 LTS (but is upgrading to 14.04 soon). For now, the script
  # compiles HDF5 manually from source.
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.15-patch1.tar.gz ;
      tar -xzf hdf5-1.8.15-patch1.tar.gz ;
      cd hdf5-1.8.15-patch1 && ./configure --build=x86_64-unknown-linux-gnu --prefix=/usr && make > /dev/null 2> /dev/null && sudo make install && cd .. ;
    fi

#
# Installation script
#
# Todo: on Mac, using "install:" doesn't work here b/c it additionally
# tries to run ./configure after doing the homebrew installation.
#
script:
  # 
  # Perform the installation on linux. Since there is no documentation,
  # 'make blank-doc' is used to create dummy documentation so that
  # 'make install' does not fail. Currently, we have to use 'sudo'
  # for 'make check' because of the HDF5 I/O's to shared data.
  # 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      ./configure && make blank-doc && make && sudo make install && sudo make check;
    fi
  # 
  # Use homebrew to install the HEAD version on OSX. At the end,
  # 'acol --version' is used to double check that the install worked.
  # 
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew install homebrew/science/hdf5 && brew install automake && brew install autoconf && brew install libtool && brew tap awsteiner/science && which autoconf && brew install o2scl --with-check --HEAD && acol --version ;
    fi

notifications:
  email:
    on_success: never
    on_failure: never
