language: cpp

os:
  - linux

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      mkdir m4 ;
      autoreconf -i ;
      autoconf ;
      automake -a --gnu ;
      sudo apt-get install libgsl0-dev ;
      sudo apt-get install libboost-all-dev ;
      sudo apt-get install libhdf5-serial-dev ;
      cat /usr/lib/x86_64-linux-gnu/libhdf5_serial.settings ;
    fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      ./configure && make && make install && make test ;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew install homebrew/science/hdf5 ;
      brew tap awsteiner/science ;
      brew install o2scl --with-check --devel ;
    fi

after_failure:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      cat config.log ;
    fi

notifications:
  email:
    on_success: never
    on_failure: never