language: cpp

os:
  - linux

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      mkdir m4 ;
      autoreconf -i ;
      autoconf ;
      automake -a --gnu ;
      sudo apt-get install libgsl0-dev ;
      sudo apt-get install libboost-all-dev ;
      wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.15-patch1.tar.gz ;
      tar -xvf hdf5-1.8.15-patch1.tar.gz ;
      cd hdf5-1.8.15-patch1 && ./configure --prefix=/usr && make && sudo make install ;
    fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      ./configure && make && make install && make test ;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew install homebrew/science/hdf5 ;
      brew tap awsteiner/science ;
      brew install o2scl --with-check --devel ;
    fi

after_failure:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      cat config.log ;
    fi

notifications:
  email:
    on_success: never
    on_failure: never