
  name: o2scl
  version: '0.926.a1'
  summary: Object-oriented Scientific Computing Library
  description: |
    O2scl is a C++ library for object-oriented numerical programming. 
    It includes interpolation, differentiation, integration, roots of 
    polynomials, equation solving, minimization, constrained 
    minimization, Monte Carlo integration, simulated annealing, 
    least-squares fitting, solution of ordinary differential equations, 
    two-dimensional interpolation, Chebyshev approximation, 
    unit conversions, and file I/O with HDF5.

  grade: devel
  confinement: devmode

# 4/29/19: I used to include -libc6 in stage-packages but it
# doesn't appear to be needed any more

# 11/6/19: Trying an rpath build to simplify the use of acol
# on snap installations. The older compiler flag is needed
# because 16.04 LTS doesn't have the newer boost integration
# libraries. The rpath flag doesn't seem to do anything at
# the moment.

# 3/12/2020: Added O2SCL_HDF5_PRE_1_12 for old HDF5 interface

  parts:
    o2scl:
      source: https://github.com/awsteiner/o2scl.git
      plugin: autotools
      install-via: prefix
      stage-packages:
      - g++
      - make
      - libboost-all-dev
      - libreadline-dev
      - libncurses-dev
      - libhdf5-serial-dev
      - libgsl0-dev
      build: |
        mkdir -p m4 && ./autogen.sh && CXXFLAGS="-DO2SCL_OLDER_COMPILER -DO2SCL_HDF5_PRE_1_12" LDFLAGS="-Wl,-rpath -Wl,/snap/o2scl/current/lib/x86_64-linux-gnu" ./configure --enable-snap --prefix=$PWD/../install && make blank-doc && make && make install
  
