
  name: o2scl
  version: '0.922'
  summary: Object-oriented Scientific Computing Library
  description: |
    O2scl is a C++ library for object-oriented numerical programming. 
    It includes interpolation, differentiation, integration, roots of 
    polynomials, equation solving, minimization, constrained 
    minimization, Monte Carlo integration, simulated annealing, 
    least-squares fitting, solution of ordinary differential equations, 
    two-dimensional interpolation, Chebyshev approximation, 
    unit conversions, and file I/O with HDF5.

  grade: devel
  confinement: devmode
  
  parts:
    o2scl:
      source: https://github.com/awsteiner/o2scl.git
      plugin: autotools
      install-via: prefix
      stage-packages:
      - libboost-all-dev
      - libreadline-dev
      - libncurses-dev
      - libhdf5-serial-dev
      - libgsl0-dev
      - libc6
      build: |
        mkdir -p m4 && ./autogen.sh && CXXFLAGS="-DO2SCL_UBUNTU_HDF5 -DO2SCL_UBUNTU_PKG" ./configure --prefix=$PWD/../install --enable-snap && make blank-doc && make && make install
  
